plugins { id 'com.android.application' }
android {
    namespace 'cn.diamond.notebook'
    compileSdk 35
    buildToolsVersion '35.0.0'
    defaultConfig { applicationId 'cn.diamond.notebook'; minSdk 26; targetSdk 35; versionCode 11; versionName '2.3.4' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
